# Generated by Django 6.0.7 on 2026-08-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productbatch_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='umbral',
            field=models.PositiveIntegerField(default=10, verbose_name='Umbral de stock'),
        ),
    ]
