"""
Django settings for library_ghostitzer project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES
# ============================================================

load_dotenv(BASE_DIR / ".env")


IP_DESTINO = os.getenv(
    "IP_DESTINO",
    ""
)


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-change-this-in-production"
)


DEBUG = os.getenv(
    "DEBUG",
    "True"
).lower() in {
    "1",
    "true",
    "yes",
    "on"
}


allowed_hosts_env = os.getenv(
    "ALLOWED_HOSTS",
    ""
).split(",")


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
] + [
    host.strip()
    for host in allowed_hosts_env
    if host.strip()
]


CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000"
    ).split(",")
    if origin.strip()
]


if not DEBUG:

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https"
    )

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    "django.contrib.admin",

    "django.contrib.auth",

    "django.contrib.contenttypes",

    "django.contrib.sessions",

    "django.contrib.messages",

    "django.contrib.staticfiles",

    "core",

    "apps.accounts",

    "apps.products",

    "apps.orders",

    "payment_simulation",

    "django_extensions",

    "rest_framework",

    "corsheaders",

    "storages",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URLS
# ============================================================

ROOT_URLCONF = "library_ghostitzer.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [

    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates"
        ],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

                "apps.accounts.context_processors.accessibility_preferences",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "library_ghostitzer.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

DATABASE_URL = os.getenv(
    "DATABASE_URL"
)


DJANGO_ENV = os.getenv(
    "DJANGO_ENV",
    "development" if DEBUG else "production"
).lower()


DB_NAME = os.getenv(
    "DB_NAME",
    ""
)


if DATABASE_URL:

    DATABASES = {

        "default": dj_database_url.config(

            default=DATABASE_URL,

            conn_max_age=600,

            ssl_require=True,
        )
    }


elif DB_NAME:

    DATABASES = {

        "default": {

            "ENGINE":
                "django.db.backends.mysql",

            "NAME":
                DB_NAME,

            "USER":
                os.getenv(
                    "DB_USER",
                    "root"
                ),

            "PASSWORD":
                os.getenv(
                    "DB_PASSWORD",
                    "admin123"
                ),

            "HOST":
                os.getenv(
                    "DB_HOST",
                    "localhost"
                ),

            "PORT":
                os.getenv(
                    "DB_PORT",
                    "3306"
                ),

            "OPTIONS": {

                "charset":
                    "utf8mb4",
            },
        }
    }


else:

    DATABASES = {

        "default": {

            "ENGINE":
                "django.db.backends.sqlite3",

            "NAME":
                BASE_DIR / "db.sqlite3",
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "es"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


STATICFILES_DIRS = [

    BASE_DIR / "static",
]


# ============================================================
# SUPABASE STORAGE
# ============================================================

USE_SUPABASE_STORAGE = os.getenv(
    "USE_SUPABASE_STORAGE",
    "False"
).lower() in {
    "1",
    "true",
    "yes",
    "on"
}


# ------------------------------------------------------------
# URL PRINCIPAL DE SUPABASE
#
# Ejemplo:
#
# https://xxxxxxxx.supabase.co
# ------------------------------------------------------------

SUPABASE_URL = os.getenv(
    "SUPABASE_URL",
    ""
).rstrip("/")


# ------------------------------------------------------------
# CREDENCIALES S3
# ------------------------------------------------------------

AWS_ACCESS_KEY_ID = os.getenv(
    "SUPABASE_S3_ACCESS_KEY_ID"
)


AWS_SECRET_ACCESS_KEY = os.getenv(
    "SUPABASE_S3_SECRET_ACCESS_KEY"
)


# ------------------------------------------------------------
# ENDPOINT S3
#
# Ejemplo:
#
# https://xxxxxxxx.storage.supabase.co/storage/v1/s3
# ------------------------------------------------------------

AWS_S3_ENDPOINT_URL = os.getenv(
    "SUPABASE_S3_ENDPOINT_URL"
)


AWS_S3_REGION_NAME = os.getenv(
    "SUPABASE_S3_REGION_NAME",
    "us-east-1"
)


AWS_S3_ADDRESSING_STYLE = "path"


AWS_DEFAULT_ACL = None


# ------------------------------------------------------------
# STORAGE
# ------------------------------------------------------------

if USE_SUPABASE_STORAGE:

    STORAGES = {

        "default": {

            "BACKEND":
                "library_ghostitzer.storage_backends.ProductsStorage",
        },

        "staticfiles": {

            "BACKEND":
                "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


    # Bucket público de productos

    _productos_bucket = os.getenv(
        "SUPABASE_STORAGE_BUCKET_PRODUCTOS",
        "productos"
    )


    # URL pública de imágenes

    MEDIA_URL = (

        f"{SUPABASE_URL}"
        f"/storage/v1/object/public/"
        f"{_productos_bucket}/"
    )


else:

    STORAGES = {

        "default": {

            "BACKEND":
                "django.core.files.storage.FileSystemStorage",
        },

        "staticfiles": {

            "BACKEND":
                "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


    MEDIA_URL = "/media/"

    MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# LOGIN
# ============================================================

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "home"


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ============================================================
# EMAIL
# ============================================================

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
)


EMAIL_HOST = os.getenv(
    "EMAIL_HOST",
    "smtp.gmail.com"
)


EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        "587"
    )
)


EMAIL_USE_TLS = os.getenv(
    "EMAIL_USE_TLS",
    "True"
) == "True"


EMAIL_USE_SSL = os.getenv(
    "EMAIL_USE_SSL",
    "False"
) == "True"


EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    ""
)


EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
    ""
)


DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Libreria Ghostitzer <noreply@libreriaghostitzer.com>"
)


COMPANY_NAME = os.getenv(
    "COMPANY_NAME",
    "Libreria Ghostitzer"
)


COMPANY_EMAIL = os.getenv(
    "COMPANY_EMAIL",
    ""
)


COMPANY_DOMAIN = os.getenv(
    "COMPANY_DOMAIN",
    "localhost:8000"
)


USE_HTTPS = os.getenv(
    "USE_HTTPS",
    "False"
) == "True"


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {

    "DEFAULT_RENDERER_CLASSES": [

        "rest_framework.renderers.JSONRenderer",
    ],

    "DEFAULT_PARSER_CLASSES": [

        "rest_framework.parsers.JSONParser",
    ],
}


# ============================================================
# CORS
# ============================================================

CORS_ALLOW_ALL_ORIGINS = os.getenv(
    "CORS_ALLOW_ALL_ORIGINS",
    "True"
).lower() in {
    "1",
    "true",
    "yes",
    "on"
}